name: 'Spell Check and Grammar Check Action'
description: 'A GitHub Action to check spelling and grammar in markdown files using OpenAI GPT-4, posting comments on pull requests.'

author: 'RR'
branding:
  color: 'blue'
  icon: 'book'

inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
    type: string

  github_repository:
    description: 'The name of the GitHub repository'
    required: true
    type: string

  github_token:
    description: 'GitHub Token to post comments on the pull request'
    required: true
    type: string

  pr_number:
    description: 'Pull request number where comments will be posted'
    required: true
    type: string

  files:
    description: 'Comma-separated list of markdown files to check for spelling and grammar'
    required: true
    type: string

runs:
  using: 'docker'
  image: 'Dockerfile'

permissions:
  contents: read
  pull-requests: write
